### ISSUE TITLE
Milestone 3 - Python Checklist

### ISSUE THREAD

**Issue by lynnwbl** [UBC-MDS/textfeatureinfo#34]
- [x] Documentation (deployed by ReadTheDocs)
  - Docstrings rendered using `napolean` Sphinx extension - Lynn
  - Include demonstration of how to use each function in the package - Lynn
  - Cosmetics for docstrings - Jacqueline

- [x] Modify `.github/workflows/ci-cd.yml` file
  - Make sure `ci-cd.yml` is correctly configured and runs the test suite and style checkers on pushes and pull requests to your project’s repository’s deployment branch (typically the main branch) - Kiran
  - Deploy to TestPyPI and PyPI on pushes to main - Kiran
  - secrets - done by Paniz

- [x] Before submission, confirm workflow run completed succesfully - Paniz
